# Generated by Django 5.2.11 on 2026-02-04 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_communities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='community',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderated_communities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitymembership',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.community'),
        ),
        migrations.AddField(
            model_name='communitymembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(related_name='joined_communities', through='communities.CommunityMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='communitymembership',
            unique_together={('user', 'community')},
        ),
    ]
